tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "neovim/neovim"
brew "bat"
brew "bison"
brew "diff-so-fancy"
brew "exa"
brew "fzf"
brew "git"
brew "jq"
brew "neovim"
brew "node@12", link: true
brew "postgresql@11"
brew "ripgrep"
brew "terraform@0.12", link: true
cask "iterm2"
cask "licecap"
cask "ngrok"
cask "postico"
cask "rectangle"
cask "spectacle"
